# Generated by Django 2.1.1 on 2021-07-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_date',
            new_name='contact_date',
        ),
    ]
